#include <DiscreteMorseFunction.h>
#include <Triangulation.h>
#include <ttkPhatWriter.h>
#include <ttkUtils.h>

#include <array>

#include <vtkDataArray.h>
#include <vtkExecutive.h>
#include <vtkImageData.h>
#include <vtkInformation.h>
#include <vtkObjectFactory.h>
#include <vtkPointData.h>
#include <vtkUnstructuredGrid.h>

vtkStandardNewMacro(ttkPhatWriter);

ttkPhatWriter::ttkPhatWriter() {
  this->SetNumberOfInputPorts(1);
  this->setDebugMsgPrefix("PhatWriter");
  this->SetDebugLevel(3);
}

int ttkPhatWriter::FillInputPortInformation(int port, vtkInformation *info) {
  if(port == 0) {
    info->Set(vtkAlgorithm::INPUT_REQUIRED_DATA_TYPE(), "vtkDataSet");
    return 1;
  }
  return 0;
}

int ttkPhatWriter::OpenFile() {

  std::ofstream f(Filename, ios::out);

  if(!f.fail()) {
    Stream = std::move(f);
  } else {
    return -1;
  }

  return 0;
}

template <typename T>
void writeBin(std::ofstream &stream, const T var) {
  stream.write(reinterpret_cast<const char *>(&var), sizeof(var));
}

vtkDataArray *getValidArray(vtkPointData *const pd) {
  if(pd == nullptr) {
    return {};
  }

  // get first data array of input point data that is not generated by
  // Resample to Image
  vtkDataArray *arr{};

  // avoid "vtkGhostType" arrays generated by Resample to Image
  std::string ghost{vtkDataSetAttributes::GhostArrayName()};
  std::string ptmask{"vtkValidPointMask"};

  for(int i = 0; i < pd->GetNumberOfArrays(); ++i) {
    arr = pd->GetArray(i);
    if(arr != nullptr && arr->GetName() != ghost && arr->GetName() != ptmask) {
      break;
    }
  }
  if(arr == nullptr || arr->GetName() == ghost || arr->GetName() == ptmask) {
    return {};
  }

  return arr;
}

int ttkPhatWriter::writeUnstructuredGrid(vtkDataObject *input) {
  const auto dataSet = vtkUnstructuredGrid::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkUnstructuredGrid");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  auto triangulation = ttkAlgorithm::GetTriangulation(dataSet);
  if(triangulation == nullptr) {
    this->printErr("Missing triangulation");
    return 0;
  }
  const auto dim = triangulation->getDimensionality();
  // precondition triangulation
  triangulation->preconditionEdges();
  if(dim > 2) {
    triangulation->preconditionTriangles();
    triangulation->preconditionTriangleEdges();
    triangulation->preconditionCellTriangles();
  }

  const auto nVerts = triangulation->getNumberOfVertices();
  const auto nEdges = triangulation->getNumberOfEdges();
  const auto nTri = (dim > 1) ? triangulation->getNumberOfTriangles() : 0;
  const auto nTetra = (dim > 2) ? triangulation->getNumberOfCells() : 0;

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }

  ttk::DiscreteMorseFunction dmf{};
  dmf.setThreadNumber(this->threadNumber_);
  dmf.setDebugLevel(this->debugLevel_);
  const auto filtOrder = dmf.computeFiltrationOrder(
    ttkUtils::GetPointer<ttk::SimplexId>(arr), *triangulation);

  std::array<std::vector<SimplexId>, 4> cellPos{};
  for(size_t i = 0; i < cellPos.size(); ++i) {
    auto &vec{cellPos[i]};
    if(i == 0) {
      vec.resize(nVerts);
    } else if(i == 1) {
      vec.resize(nEdges);
    } else if(i == 2) {
      vec.resize(nTri);
    } else if(i == 3) {
      vec.resize(nTetra);
    }
  }
  for(size_t i = 0; i < filtOrder.size(); ++i) {
    const auto &c{filtOrder[i]};
    cellPos[c.dim_][c.id_] = i;
  }

  for(const auto &c : filtOrder) {
    // cell dimension
    Stream << c.dim_ << " ";
    // cell boundary size
    Stream << (c.dim_ > 0 ? c.dim_ + 1 : 0) << " ";
    // cell boundary
    if(c.dim_ == 0) {
      Stream << '\n';
      continue;
    }
    for(int i = 0; i < c.dim_ + 1; ++i) {
      SimplexId v{};
      if(c.dim_ == 1) {
        triangulation->getEdgeVertex(c.id_, i, v);
      } else if(c.dim_ == 2) {
        triangulation->getTriangleEdge(c.id_, i, v);
      } else if(c.dim_ == 3) {
        triangulation->getCellTriangle(c.id_, i, v);
      }
      Stream << cellPos[c.dim_ - 1][v] << " ";
    }
    Stream << '\n';
  }

  return 1;
}

int ttkPhatWriter::Write() {
  ttk::Timer tm{};

  const auto dataset = this->GetInput();
  int ret{};
  if(dataset->IsA("vtkUnstructuredGrid")) {
    ret = writeUnstructuredGrid(dataset);
  }

  this->printMsg("Wrote file", 1.0, tm.getElapsedTime(), 1);
  return ret;
}

vtkDataObject *ttkPhatWriter::GetInput() {
  // copied from ParaView's vtkWriter::GetInput()
  if(this->GetNumberOfInputConnections(0) < 1) {
    return nullptr;
  }
  return this->GetExecutive()->GetInputData(0, 0);
}

void ttkPhatWriter::SetInputData(vtkDataObject *input) {
  // copied from ParaView's vtkWriter::SetInputData()
  this->SetInputDataInternal(0, input);
}
