#include <Triangulation.h>
#include <ttkSimplicialComplexWriter.h>

#include <array>
#include <cstring>

#include <vtkDataArray.h>
#include <vtkExecutive.h>
#include <vtkImageData.h>
#include <vtkInformation.h>
#include <vtkObjectFactory.h>
#include <vtkPointData.h>
#include <vtkUnstructuredGrid.h>

vtkStandardNewMacro(ttkSimplicialComplexWriter);

ttkSimplicialComplexWriter::ttkSimplicialComplexWriter() {
  this->SetNumberOfInputPorts(1);
  this->setDebugMsgPrefix("SimplicialComplexWriter");
  this->setDebugLevel(3);
}

int ttkSimplicialComplexWriter::FillInputPortInformation(int port,
                                                         vtkInformation *info) {
  if(port == 0) {
    info->Set(vtkAlgorithm::INPUT_REQUIRED_DATA_TYPE(), "vtkUnstructuredGrid");
    return 1;
  }
  return 0;
}

int ttkSimplicialComplexWriter::OpenFile() {

  std::ofstream f(Filename, ios::out | ios::binary);

  if(!f.fail()) {
    Stream = std::move(f);
  } else {
    return -1;
  }

  return 0;
}

template <typename T>
void writeBin(std::ofstream &stream, const T var) {
  stream.write(reinterpret_cast<const char *>(&var), sizeof(var));
}

vtkDataArray *getValidArray(vtkPointData *const pd) {
  if(pd == nullptr) {
    return {};
  }

  // get first data array of input point data that is not generated by
  // Resample to Image
  vtkDataArray *arr{};

  // avoid "vtkGhostType" arrays generated by Resample to Image
  std::string ghost{vtkDataSetAttributes::GhostArrayName()};
  std::string ptmask{"vtkValidPointMask"};

  for(int i = 0; i < pd->GetNumberOfArrays(); ++i) {
    arr = pd->GetArray(i);
    if(arr != nullptr && arr->GetName() != ghost && arr->GetName() != ptmask) {
      break;
    }
  }
  if(arr == nullptr || arr->GetName() == ghost || arr->GetName() == ptmask) {
    return {};
  }

  return arr;
}

int ttkSimplicialComplexWriter::writeUnstructuredGrid(vtkDataObject *input) {
  const auto dataSet = vtkUnstructuredGrid::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkImageData");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  auto triangulation = ttkAlgorithm::GetTriangulation(dataSet);
  if(triangulation == nullptr) {
    this->printErr("Missing triangulation");
    return 0;
  }
  const auto dim = triangulation->getDimensionality();
  // precondition triangulation
  triangulation->preconditionEdges();
  if(dim > 2) {
    triangulation->preconditionTriangles();
  }

  // magic number
  const char magic[] = "TTKSimplicialComplex";
  Stream.write(magic, std::strlen(magic));

  // global number of cells (vertices + edges + triangles + tetras)
  const auto nVerts = triangulation->getNumberOfVertices();
  const auto nEdges = triangulation->getNumberOfEdges();
  const auto nTri = dim > 1 ? triangulation->getNumberOfTriangles() : 0;
  const auto nTetra = dim > 2 ? triangulation->getNumberOfCells() : 0;
  const auto num_simplices = nVerts + nEdges + nTri + nTetra;
  writeBin<ttk::SimplexId>(Stream, num_simplices);

  // max dimension
  writeBin<ttk::SimplexId>(Stream, dim);

  // number of cells per dimensions
  writeBin<ttk::SimplexId>(Stream, nVerts);
  writeBin<ttk::SimplexId>(Stream, nEdges);
  writeBin<ttk::SimplexId>(Stream, nTri);
  writeBin<ttk::SimplexId>(Stream, nTetra);

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }

  // cell values (max vertex value)
  using ttk::SimplexId;
  for(int i = 0; i < nVerts; ++i) {
    writeBin<double>(Stream, arr->GetTuple1(i));
  }
  for(int i = 0; i < nEdges; ++i) {
    SimplexId v0{}, v1{};
    triangulation->getEdgeVertex(i, 0, v0);
    triangulation->getEdgeVertex(i, 1, v1);
    writeBin<double>(Stream, std::max(arr->GetTuple1(v0), arr->GetTuple1(v1)));
  }
  for(int i = 0; i < nTri; ++i) {
    SimplexId v0{}, v1{}, v2{};
    triangulation->getTriangleVertex(i, 0, v0);
    triangulation->getTriangleVertex(i, 1, v1);
    triangulation->getTriangleVertex(i, 2, v2);
    writeBin<double>(
      Stream, std::max(std::max(arr->GetTuple1(v0), arr->GetTuple1(v1)),
                       arr->GetTuple1(v2)));
  }
  for(int i = 0; i < nTetra; ++i) {
    SimplexId v0{}, v1{}, v2{}, v3{};
    triangulation->getCellVertex(i, 0, v0);
    triangulation->getCellVertex(i, 1, v1);
    triangulation->getCellVertex(i, 2, v2);
    triangulation->getCellVertex(i, 3, v3);
    writeBin<double>(
      Stream, std::max(std::max(arr->GetTuple1(v0), arr->GetTuple1(v1)),
                       std::max(arr->GetTuple1(v2), arr->GetTuple1(v3))));
  }

  // number of entries in the boundary matrix
  const auto num_entries = 2 * nEdges + 3 * nTri + 4 * nTetra;
  writeBin<ttk::SimplexId>(Stream, num_entries);

  // flattened boundary matrix
  for(int i = 0; i < nEdges; ++i) {
    SimplexId v0{}, v1{};
    triangulation->getEdgeVertex(i, 0, v0);
    triangulation->getEdgeVertex(i, 1, v1);
    writeBin<ttk::SimplexId>(Stream, v0);
    writeBin<ttk::SimplexId>(Stream, v1);
  }
  for(int i = 0; i < nTri; ++i) {
    SimplexId v0{}, v1{}, v2{};
    triangulation->getTriangleVertex(i, 0, v0);
    triangulation->getTriangleVertex(i, 1, v1);
    triangulation->getTriangleVertex(i, 2, v2);
    writeBin<ttk::SimplexId>(Stream, v0);
    writeBin<ttk::SimplexId>(Stream, v1);
    writeBin<ttk::SimplexId>(Stream, v2);
  }
  for(int i = 0; i < nTetra; ++i) {
    std::array<SimplexId, 4> v{};
    triangulation->getCellVertex(i, 0, v[0]);
    triangulation->getCellVertex(i, 1, v[1]);
    triangulation->getCellVertex(i, 2, v[2]);
    triangulation->getCellVertex(i, 3, v[3]);
    // sort cell vertices in increasing order
    std::sort(v.begin(), v.end());
    writeBin<ttk::SimplexId>(Stream, v[0]);
    writeBin<ttk::SimplexId>(Stream, v[1]);
    writeBin<ttk::SimplexId>(Stream, v[2]);
    writeBin<ttk::SimplexId>(Stream, v[3]);
  }
  return 1;
}

int ttkSimplicialComplexWriter::Write() {
  ttk::Timer tm{};

  const auto dataset = this->GetInput();
  int ret{};
  if(dataset->IsA("vtkUnstructuredGrid")) {
    ret = writeUnstructuredGrid(dataset);
  }

  this->printMsg("Wrote file", 1.0, tm.getElapsedTime(), 1);
  return ret;
}

vtkDataObject *ttkSimplicialComplexWriter::GetInput() {
  // copied from ParaView's vtkWriter::GetInput()
  if(this->GetNumberOfInputConnections(0) < 1) {
    return nullptr;
  }
  return this->GetExecutive()->GetInputData(0, 0);
}

void ttkSimplicialComplexWriter::SetInputData(vtkDataObject *input) {
  // copied from ParaView's vtkWriter::SetInputData()
  this->SetInputDataInternal(0, input);
}
