#include <Triangulation.h>
#include <ttkPerseusWriter.h>
#include <ttkUtils.h>

#include <array>
#include <numeric>

#include <vtkDataArray.h>
#include <vtkExecutive.h>
#include <vtkImageData.h>
#include <vtkInformation.h>
#include <vtkObjectFactory.h>
#include <vtkPointData.h>
#include <vtkUnstructuredGrid.h>

vtkStandardNewMacro(ttkPerseusWriter);

ttkPerseusWriter::ttkPerseusWriter() {
  this->SetNumberOfInputPorts(1);
  this->setDebugMsgPrefix("PerseusWriter");
  this->SetDebugLevel(3);
}

int ttkPerseusWriter::FillInputPortInformation(int port, vtkInformation *info) {
  if(port == 0) {
    info->Set(vtkAlgorithm::INPUT_REQUIRED_DATA_TYPE(), "vtkDataSet");
    return 1;
  }
  return 0;
}

int ttkPerseusWriter::OpenFile() {

  std::ofstream f(Filename, ios::out);

  if(!f.fail()) {
    Stream = std::move(f);
  } else {
    return -1;
  }

  return 0;
}

vtkDataArray *getValidArray(vtkPointData *const pd) {
  if(pd == nullptr) {
    return {};
  }

  // get first data array of input point data that is not generated by
  // Resample to Image
  vtkDataArray *arr{};

  // avoid "vtkGhostType" arrays generated by Resample to Image
  std::string ghost{vtkDataSetAttributes::GhostArrayName()};
  std::string ptmask{"vtkValidPointMask"};

  for(int i = 0; i < pd->GetNumberOfArrays(); ++i) {
    arr = pd->GetArray(i);
    if(arr != nullptr && arr->GetName() != ghost && arr->GetName() != ptmask) {
      break;
    }
  }
  if(arr == nullptr || arr->GetName() == ghost || arr->GetName() == ptmask) {
    return {};
  }

  return arr;
}

int ttkPerseusWriter::writeImageData(vtkDataObject *input) {

  const auto dataSet = vtkImageData::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkImageData");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  // dimension
  std::array<int, 3> dims{};
  dataSet->GetDimensions(dims.data());
  int dim = dims[2] == 1 ? 2 : 3;
  Stream << dim << '\n';

  // resolution
  for(int i = 0; i < dim; ++i) {
    Stream << dims[i] << '\n';
  }

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }
  if(arr->GetNumberOfComponents() != 1) {
    this->printErr("Data array should have only 1 component");
    return 0;
  }
  for(int i = 0; i < arr->GetNumberOfTuples(); ++i) {
    Stream << static_cast<long long>(arr->GetTuple1(i)) << '\n';
  }

  return 1;
}

int ttkPerseusWriter::writeUnstructuredGrid(vtkDataObject *input) {

  const auto dataSet = vtkUnstructuredGrid::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkUnstructuredGrid");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }

  using ttk::SimplexId;

  // compute order on scalar field array
  std::vector<SimplexId> newOrderArray(arr->GetNumberOfTuples());

  switch(arr->GetDataType()) {
    vtkTemplateMacro(ttk::preconditionOrderArray(
      arr->GetNumberOfTuples(),
      static_cast<VTK_TT *>(ttkUtils::GetVoidPointer(arr)),
      newOrderArray.data(), this->threadNumber_));
  }

  auto triangulation = ttkAlgorithm::GetTriangulation(dataSet);
  if(triangulation == nullptr) {
    this->printErr("Missing triangulation");
    return 0;
  }

  if(triangulation->getNumberOfVertices() != arr->GetNumberOfTuples()) {
    this->printErr("Mismatch between triangulation and scalar field array");
    return 0;
  }

  // dimensionality
  const auto dim = triangulation->getDimensionality();
  Stream << dim << '\n';
  // ambient dimension of the vertices (use natural ordering)
  Stream << 1 << '\n';

  const auto nCells = triangulation->getNumberOfCells();
  if(nCells < 1) {
    this->printErr("Triangulation has no cells");
    return 0;
  }

  // assume uniform triangulation
  const auto nVertsCell = triangulation->getCellVertexNumber(0);
  if(nCells < 1) {
    this->printErr("Triangulation cell has no vertices");
    return 0;
  }

  // write cell vertices + cell order to file
  for(SimplexId i = 0; i < nCells; ++i) {
    std::array<SimplexId, 4> cellVertsOrder{};
    for(SimplexId j = 0; j < nVertsCell; ++j) {
      SimplexId v{};
      triangulation->getCellVertex(i, j, v);
      Stream << v << " ";
      cellVertsOrder[j] = newOrderArray[v];
    }
    Stream << *std::max_element(cellVertsOrder.begin(), cellVertsOrder.end())
           << '\n';
  }

  return 1;
}

int ttkPerseusWriter::Write() {
  ttk::Timer tm{};

  const auto dataset = this->GetInput();
  int ret{};
  if(dataset->IsA("vtkImageData")) {
    ret = writeImageData(dataset);
  } else if(dataset->IsA("vtkUnstructuredGrid")) {
    ret = writeUnstructuredGrid(dataset);
  }

  this->printMsg("Wrote file", 1.0, tm.getElapsedTime(), 1);
  return ret;
}

vtkDataObject *ttkPerseusWriter::GetInput() {
  // copied from ParaView's vtkWriter::GetInput()
  if(this->GetNumberOfInputConnections(0) < 1) {
    return nullptr;
  }
  return this->GetExecutive()->GetInputData(0, 0);
}

void ttkPerseusWriter::SetInputData(vtkDataObject *input) {
  // copied from ParaView's vtkWriter::SetInputData()
  this->SetInputDataInternal(0, input);
}
