#include <Triangulation.h>
#include <ttkEireneWriter.h>

#include <array>

#ifdef TTK_ENABLE_EIGEN
#include <Eigen/Sparse>
#endif // TTK_ENABLE_EIGEN

#include <vtkDataArray.h>
#include <vtkExecutive.h>
#include <vtkInformation.h>
#include <vtkObjectFactory.h>
#include <vtkPointData.h>
#include <vtkUnstructuredGrid.h>

vtkStandardNewMacro(ttkEireneWriter);

ttkEireneWriter::ttkEireneWriter() {
  this->SetNumberOfInputPorts(1);
  this->setDebugMsgPrefix("EireneWriter");
  this->setDebugLevel(3);
}

int ttkEireneWriter::FillInputPortInformation(int port, vtkInformation *info) {
  if(port == 0) {
    info->Set(vtkAlgorithm::INPUT_REQUIRED_DATA_TYPE(), "vtkDataSet");
    return 1;
  }
  return 0;
}

int ttkEireneWriter::OpenFile() {

  std::ofstream f(Filename);

  if(!f.fail()) {
    Stream = std::move(f);
  } else {
    return -1;
  }

  return 0;
}

template <typename T>
void writeBin(std::ofstream &stream, const T var) {
  stream.write(reinterpret_cast<const char *>(&var), sizeof(var));
}

vtkDataArray *getValidArray(vtkPointData *const pd) {
  if(pd == nullptr) {
    return {};
  }

  // get first data array of input point data that is not generated by
  // Resample to Image
  vtkDataArray *arr{};

  // avoid "vtkGhostType" arrays generated by Resample to Image
  std::string ghost{vtkDataSetAttributes::GhostArrayName()};
  std::string ptmask{"vtkValidPointMask"};

  for(int i = 0; i < pd->GetNumberOfArrays(); ++i) {
    arr = pd->GetArray(i);
    if(arr != nullptr && arr->GetName() != ghost && arr->GetName() != ptmask) {
      break;
    }
  }
  if(arr == nullptr || arr->GetName() == ghost || arr->GetName() == ptmask) {
    return {};
  }

  return arr;
}

int ttkEireneWriter::writeUnstructuredGrid(vtkDataObject *input) {
  const auto dataSet = vtkUnstructuredGrid::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkUnstructuredGrid");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  auto triangulation = ttkAlgorithm::GetTriangulation(dataSet);
  if(triangulation == nullptr) {
    this->printErr("Missing triangulation");
    return 0;
  }
  const auto dim = triangulation->getDimensionality();
  // precondition triangulation
  triangulation->preconditionEdges();
  if(dim > 2) {
    triangulation->preconditionTriangles();
    triangulation->preconditionTriangleEdges();
    triangulation->preconditionCellTriangles();
  }

  // global number of cells (vertices + edges + triangles + tetras)
  const auto nVerts = triangulation->getNumberOfVertices();
  const auto nEdges = triangulation->getNumberOfEdges();
  const auto nTri = dim > 1 ? triangulation->getNumberOfTriangles() : 0;
  const auto nTetra = dim == 3 ? triangulation->getNumberOfCells() : 0;
  const auto num_simplices = nVerts + nEdges + nTri + nTetra;

  // ev: cell dimensions
  Stream << nVerts << ',' << nEdges;
  if(dim > 1) {
    Stream << ',' << nTri;
  }
  if(dim > 2) {
    Stream << ',' << nTetra;
  }
  Stream << '\n';

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }

  // fv: cell values (max vertex value)
  using ttk::SimplexId;
  Stream << arr->GetTuple1(0);
  for(int i = 1; i < nVerts; ++i) {
    Stream << ',' << arr->GetTuple1(i);
  }
  for(int i = 0; i < nEdges; ++i) {
    SimplexId v0{}, v1{};
    triangulation->getEdgeVertex(i, 0, v0);
    triangulation->getEdgeVertex(i, 1, v1);
    Stream << ',' << std::max(arr->GetTuple1(v0), arr->GetTuple1(v1));
  }
  for(int i = 0; i < nTri; ++i) {
    SimplexId v0{}, v1{}, v2{};
    triangulation->getTriangleVertex(i, 0, v0);
    triangulation->getTriangleVertex(i, 1, v1);
    triangulation->getTriangleVertex(i, 2, v2);
    Stream << ','
           << std::max(std::max(arr->GetTuple1(v0), arr->GetTuple1(v1)),
                       arr->GetTuple1(v2));
  }
  for(int i = 0; i < nTetra; ++i) {
    SimplexId v0{}, v1{}, v2{}, v3{};
    triangulation->getCellVertex(i, 0, v0);
    triangulation->getCellVertex(i, 1, v1);
    triangulation->getCellVertex(i, 2, v2);
    triangulation->getCellVertex(i, 3, v3);
    Stream << ','
           << std::max(std::max(arr->GetTuple1(v0), arr->GetTuple1(v1)),
                       std::max(arr->GetTuple1(v2), arr->GetTuple1(v3)));
  }
  Stream << '\n';

  // number of entries in the boundary matrix
  const auto num_entries = 2 * nEdges + 3 * nTri + 4 * nTetra;

  if(num_entries == 0) {
    this->printErr("Empty boundary matrix!");
    return 0;
  }

#ifdef TTK_ENABLE_EIGEN

  // flattened boundary matrix
  std::vector<Eigen::Triplet<unsigned char>> triplets(num_entries);

#ifdef TTK_ENABLE_OPENMP
#pragma omp parallel for num_threads(this->threadNumber_)
#endif // TTK_ENABLE_OPENMP
  for(int i = 0; i < nEdges; ++i) {
    SimplexId v0{}, v1{};
    triangulation->getEdgeVertex(i, 0, v0);
    triangulation->getEdgeVertex(i, 1, v1);
    triplets[2 * i + 0] = {v0, i + nVerts, 1};
    triplets[2 * i + 1] = {v1, i + nVerts, 1};
  }

#ifdef TTK_ENABLE_OPENMP
#pragma omp parallel for num_threads(this->threadNumber_)
#endif // TTK_ENABLE_OPENMP
  for(int i = 0; i < nTri; ++i) {
    SimplexId e0{}, e1{}, e2{};
    triangulation->getTriangleEdge(i, 0, e0);
    triangulation->getTriangleEdge(i, 1, e1);
    triangulation->getTriangleEdge(i, 2, e2);
    const auto o = 3 * i + 2 * nEdges;
    triplets[o + 0] = {e0 + nVerts, i + nVerts + nEdges, 1};
    triplets[o + 1] = {e1 + nVerts, i + nVerts + nEdges, 1};
    triplets[o + 2] = {e2 + nVerts, i + nVerts + nEdges, 1};
  }

#ifdef TTK_ENABLE_OPENMP
#pragma omp parallel for num_threads(this->threadNumber_)
#endif // TTK_ENABLE_OPENMP
  for(int i = 0; i < nTetra; ++i) {
    SimplexId t0{}, t1{}, t2{}, t3{};
    triangulation->getCellTriangle(i, 0, t0);
    triangulation->getCellTriangle(i, 1, t1);
    triangulation->getCellTriangle(i, 2, t2);
    triangulation->getCellTriangle(i, 3, t3);
    const auto o = 4 * i + 2 * nEdges + 3 * nTri;
    triplets[o + 0] = {t0 + nVerts + nEdges, i + nVerts + nEdges + nTri, 1};
    triplets[o + 1] = {t1 + nVerts + nEdges, i + nVerts + nEdges + nTri, 1};
    triplets[o + 2] = {t2 + nVerts + nEdges, i + nVerts + nEdges + nTri, 1};
    triplets[o + 3] = {t3 + nVerts + nEdges, i + nVerts + nEdges + nTri, 1};
  }

  Eigen::SparseMatrix<unsigned char> spmat{};
  spmat.resize(num_simplices, num_simplices);
  spmat.setFromTriplets(triplets.begin(), triplets.end());
  spmat.makeCompressed();

  // rv
  Stream << spmat.innerIndexPtr()[0] + 1; // (Julia is 1-indexed)
  for(int i = 1; i < num_entries; ++i) {
    Stream << ',' << spmat.innerIndexPtr()[i] + 1; // (Julia is 1-indexed)
  }
  Stream << '\n';

  // cp
  Stream << spmat.outerIndexPtr()[0] + 1; // (Julia is 1-indexed)
  for(int i = 1; i < spmat.cols() + 1; ++i) {
    Stream << ',' << spmat.outerIndexPtr()[i] + 1; // (Julia is 1-indexed)
  }
  Stream << '\n';

#else

  this->printErr("Need Eigen to generate Eirene.jl CSV Sparse Column Format");

#endif // TTK_ENABLE_EIGEN

  return 1;
}

int ttkEireneWriter::Write() {
  ttk::Timer tm{};

  const auto dataset = this->GetInput();
  int ret{};
  if(dataset->IsA("vtkUnstructuredGrid")) {
    ret = writeUnstructuredGrid(dataset);
  }

  this->printMsg("Wrote file", 1.0, tm.getElapsedTime(), 1);
  return ret;
}

vtkDataObject *ttkEireneWriter::GetInput() {
  // copied from ParaView's vtkWriter::GetInput()
  if(this->GetNumberOfInputConnections(0) < 1) {
    return nullptr;
  }
  return this->GetExecutive()->GetInputData(0, 0);
}

void ttkEireneWriter::SetInputData(vtkDataObject *input) {
  // copied from ParaView's vtkWriter::SetInputData()
  this->SetInputDataInternal(0, input);
}
