#include <Triangulation.h>
#include <ttkOineusWriter.h>
#include <ttkUtils.h>

#include <array>

#include <vtkDataArray.h>
#include <vtkExecutive.h>
#include <vtkImageData.h>
#include <vtkInformation.h>
#include <vtkObjectFactory.h>
#include <vtkPointData.h>
#include <vtkUnstructuredGrid.h>

vtkStandardNewMacro(ttkOineusWriter);

ttkOineusWriter::ttkOineusWriter() {
  this->SetNumberOfInputPorts(1);
  this->setDebugMsgPrefix("OineusWriter");
  this->SetDebugLevel(3);
}

int ttkOineusWriter::FillInputPortInformation(int port, vtkInformation *info) {
  if(port == 0) {
    info->Set(vtkAlgorithm::INPUT_REQUIRED_DATA_TYPE(), "vtkDataSet");
    return 1;
  }
  return 0;
}

int ttkOineusWriter::OpenFile() {

  std::ofstream f(Filename, ios::out);

  if(!f.fail()) {
    Stream = std::move(f);
  } else {
    return -1;
  }

  return 0;
}

vtkDataArray *getValidArray(vtkPointData *const pd) {
  if(pd == nullptr) {
    return {};
  }

  // get first data array of input point data that is not generated by
  // Resample to Image
  vtkDataArray *arr{};

  // avoid "vtkGhostType" arrays generated by Resample to Image
  std::string ghost{vtkDataSetAttributes::GhostArrayName()};
  std::string ptmask{"vtkValidPointMask"};

  for(int i = 0; i < pd->GetNumberOfArrays(); ++i) {
    arr = pd->GetArray(i);
    if(arr != nullptr && arr->GetName() != ghost && arr->GetName() != ptmask) {
      break;
    }
  }
  if(arr == nullptr || arr->GetName() == ghost || arr->GetName() == ptmask) {
    return {};
  }

  return arr;
}

int ttkOineusWriter::writeUnstructuredGrid(vtkDataObject *input) {
  const auto dataSet = vtkUnstructuredGrid::SafeDownCast(input);

  if(dataSet == nullptr) {
    this->printErr("Requesting a vtkUnstructuredGrid");
    return 0;
  }

  if(this->OpenFile() == -1) {
    this->printErr("Could not open file `" + std::string{Filename} + "' :(");
    return 0;
  }

  auto triangulation = ttkAlgorithm::GetTriangulation(dataSet);
  if(triangulation == nullptr) {
    this->printErr("Missing triangulation");
    return 0;
  }
  const auto dim = triangulation->getDimensionality();
  // precondition triangulation
  triangulation->preconditionEdges();
  if(dim > 2) {
    triangulation->preconditionTriangles();
  }

  const auto nVerts = triangulation->getNumberOfVertices();
  const auto nEdges = triangulation->getNumberOfEdges();
  const auto nTri = (dim > 1) ? triangulation->getNumberOfTriangles() : 0;
  const auto nTetra = (dim > 2) ? triangulation->getNumberOfCells() : 0;

  // actual data (first data array)
  const auto arr = getValidArray(dataSet->GetPointData());
  if(arr == nullptr) {
    return 0;
  }

  const auto buf = ttkUtils::GetPointer<ttk::SimplexId>(arr);

  for(ttk::SimplexId i = 0; i < nVerts; ++i) {
    Stream << i << ' ' << -1 << ' ' << -1 << ' ' << -1 << ' ' << buf[i] << '\n';
  }
  for(ttk::SimplexId i = 0; i < nEdges; ++i) {
    ttk::SimplexId v0{}, v1{};
    triangulation->getEdgeVertex(i, 0, v0);
    triangulation->getEdgeVertex(i, 1, v1);
    Stream << v0 << ' ' << v1 << ' ' << -1 << ' ' << -1 << ' '
           << std::max(buf[v0], buf[v1]) << '\n';
  }
  for(ttk::SimplexId i = 0; i < nTri; ++i) {
    ttk::SimplexId v0{}, v1{}, v2{};
    triangulation->getTriangleVertex(i, 0, v0);
    triangulation->getTriangleVertex(i, 1, v1);
    triangulation->getTriangleVertex(i, 2, v2);
    Stream << v0 << ' ' << v1 << ' ' << v2 << ' ' << -1 << ' '
           << std::max(std::max(buf[v0], buf[v1]), buf[v2]) << '\n';
  }
  for(ttk::SimplexId i = 0; i < nTetra; ++i) {
    ttk::SimplexId v0{}, v1{}, v2{}, v3{};
    triangulation->getCellVertex(i, 0, v0);
    triangulation->getCellVertex(i, 1, v1);
    triangulation->getCellVertex(i, 2, v2);
    triangulation->getCellVertex(i, 3, v3);
    Stream << v0 << ' ' << v1 << ' ' << v2 << ' ' << v3 << ' '
           << std::max(std::max(buf[v0], buf[v1]), std::max(buf[v2], buf[v3]))
           << '\n';
  }

  return 1;
}

int ttkOineusWriter::Write() {
  ttk::Timer tm{};

  const auto dataset = this->GetInput();
  int ret{};
  if(dataset->IsA("vtkUnstructuredGrid")) {
    ret = writeUnstructuredGrid(dataset);
  }

  this->printMsg("Wrote file", 1.0, tm.getElapsedTime(), 1);
  return ret;
}

vtkDataObject *ttkOineusWriter::GetInput() {
  // copied from ParaView's vtkWriter::GetInput()
  if(this->GetNumberOfInputConnections(0) < 1) {
    return nullptr;
  }
  return this->GetExecutive()->GetInputData(0, 0);
}

void ttkOineusWriter::SetInputData(vtkDataObject *input) {
  // copied from ParaView's vtkWriter::SetInputData()
  this->SetInputDataInternal(0, input);
}
