name: code_coverage

on:
  push:
    branch-ignore:
      - '*'
    tags:
      - 'cov*'

env:
  PV_REPO: topology-tool-kit/ttk-paraview
  PV_TAG: v5.10.0-headless


jobs:

  coverage-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout TTK source code

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # TTK dependencies
        sudo apt install -y \
          libboost-system-dev \
          libeigen3-dev \
          libgraphviz-dev \
          libosmesa-dev \
          libsqlite3-dev \
          graphviz \
          ninja-build \
          zlib1g-dev \
          dpkg-dev
        sudo python3 -m pip install scikit-learn gcovr

    - name: Install optional dependencies
      uses: ./.github/actions/install-deps-unix

    - uses: dsaltares/fetch-gh-release-asset@master
      name: Fetch TTK-ParaView headless Debian package
      with:
        repo: "${{ env.PV_REPO }}"
        version: "tags/${{ env.PV_TAG }}"
        file: "ttk-paraview-headless-ubuntu-20.04.deb"
        target: "ttk-paraview-headless.deb"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install ParaView .deb
      run: |
        sudo apt install ./ttk-paraview-headless.deb

    - name: Create & configure TTK build directory
      run: |
        cd ..
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_FLAGS="-g --coverage" \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE \
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE \
          -GNinja \
          $GITHUB_WORKSPACE

    - name: Build & install TTK
      run: |
        cd ../build
        cmake --build . --parallel
        sudo cmake --build . --target install

    - name: Run TTK tests
      uses: ./.github/actions/test-ttk-unix

    - uses: actions/checkout@v2
      with:
        repository: "topology-tool-kit/ttk-data"
        ref: "dev"
        path: "ttk-data"
      name: Checkout ttk-data

    - name: Run ttk-data states
      if: false
      continue-on-error: true
      run: |
        cd ttk-data/tests
        mkdir output_screenshots
        python3 -u validate.py

    - name: Run ttk-data Python scripts
      run: |
        cd ttk-data
        python3 -u python/run.py
      env:
        OMP_NUM_THREADS: 1

    - name: Gather traces into coverage report
      run: |
        cd ..
        mkdir cov_report
        gcovr -r $GITHUB_WORKSPACE \
          --branches \
          --html \
          --html-details \
          --html-self-contained \
          -o cov_report/coverage.html \
          build
        tar zcf $GITHUB_WORKSPACE/cov_report.tar.gz cov_report

    - name: Upload result screenshots
      uses: actions/upload-artifact@v2
      with:
        name: cov_report.tar.gz
        path: cov_report.tar.gz
