name: hello

on:
  push:
    branches:
      - "test_ci"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PV_TAG: 5.11.0-headless
  PV_REPO: pierre-guillou/paraview-ttk

jobs:
  test-build-windows:
    runs-on: windows-2022
    env:
      PV_DIR: C:\Program Files\TTK-ParaView
      TTK_DIR: C:\Program Files (x86)\ttk
      CONDA_ROOT: C:\Miniconda
      SCCACHE_CACHE_SIZE: 200M
    steps:
      - uses: actions/checkout@v3
        name: Checkout TTK source code

      - uses: s-weigand/setup-conda@v1

      - name: Install dependencies with conda
        shell: bash
        run: |
          conda install -c conda-forge boost glew conda=4.14
          # add sccache to PATH
          echo "$CONDA_ROOT/bin" >> $GITHUB_PATH
          # add TTK & ParaView install folders to PATH
          echo "$PV_DIR/bin" >> $GITHUB_PATH
          echo "$TTK_DIR/bin" >> $GITHUB_PATH

      - name: Remove hosted Python
        shell: bash
        run: |
          rm -rf C:/hostedtoolcache/windows/Python
          ls -l "$CONDA_ROOT"

      - name: Fetch archived ccache
        continue-on-error: true
        run: |
          Invoke-WebRequest `
          -OutFile ttk-sccache.tar.gz `
          -Uri https://github.com/${{ github.repository }}/releases/download/ccache/ttk-sccache-windows.tar.gz

      - name: Decompress ccache archive
        continue-on-error: true
        shell: bash
        run: |
          tar xzf ttk-sccache.tar.gz
          mkdir -p /c/Users/runneradmin/AppData/Local/Mozilla/sccache
          mv cache /c/Users/runneradmin/AppData/Local/Mozilla/sccache

      - name: Fetch TTK-ParaView headless Windows installer
        run: |
          Invoke-WebRequest `
          -OutFile ttk-paraview-headless.exe `
          -Uri https://github.com/${{ env.PV_REPO }}/releases/download/${{ env.PV_TAG }}/ttk-paraview-headless.exe

      - name: Install ParaView
        shell: cmd
        run: |
          ttk-paraview-headless.exe /S

      - name: Test Python imports
        continue-on-error: true
        shell: cmd
        run: |
          set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
          set PV_PLUGIN_PATH=%TTK_DIR%\bin\plugins
          echo "env vars"
          set
          echo "pvpython"
          pvpython --version
          pvpython -m sysconfig
          echo "pvpython vtk"
          pvpython -m vtk
          echo "pvpython simple
          pvpython -m paraview.simple
          echo "python"
          python -m sysconfig
          echo "python vtk"
          python -m vtk
          echo "python simple
          python -m paraview.simple

      - name: Create & configure TTK build directory
        shell: cmd
        run: |
          set CMAKE_PREFIX_PATH=%CONDA_ROOT%\Library\lib\cmake;%CONDA_ROOT%\Library\share\eigen3\cmake;%CONDA_ROOT%\Library\cmake;%ProgramFiles%\TTK-ParaView\lib\cmake
          set CC=clang-cl.exe
          set CXX=clang-cl.exe
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          sccache --stop-server
          sccache --start-server
          mkdir build
          cd build
          cmake ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_POLICY_DEFAULT_CMP0092=NEW ^
            -DBUILD_SHARED_LIBS:BOOL=TRUE ^
            -DPython3_ROOT_DIR="%CONDA_ROOT%" ^
            -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE ^
            -DTTK_BUILD_VTK_WRAPPERS=TRUE ^
            -DTTK_BUILD_STANDALONE_APPS=TRUE ^
            -DTTK_ENABLE_KAMIKAZE=TRUE ^
            -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE ^
            -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE ^
            -DTTK_ENABLE_SCIKIT_LEARN=FALSE ^
            -DTTK_IMPLICIT_PRECONDITIONS_THRESHOLD=64*64*64 ^
            -G"Visual Studio 17 2022" ^
            ..

      - name: Build & install TTK
        shell: cmd
        run: |
          cd build
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build . --config Release --parallel --target install

      - name: Test C++ example
        shell: cmd
        run: |
          set CC=clang-cl.exe
          set CXX=clang-cl.exe
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set CMAKE_PREFIX_PATH=%TTK_DIR%\lib\cmake;%PV_DIR%\lib\cmake
          cd %GITHUB_WORKSPACE%\examples\c++
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --config Release --parallel
          ttkExample-c++.exe -i ..\..\data\inputData.off

      - name: Test VTK-C++ example
        shell: cmd
        run: |
          set CC=clang-cl.exe
          set CXX=clang-cl.exe
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set CMAKE_PREFIX_PATH=%TTK_DIR%\lib\cmake;%PV_DIR%\lib\cmake
          cd %GITHUB_WORKSPACE%\examples\vtk-c++
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --config Release --parallel
          ttkExample-vtk-c++.exe -i ..\..\data\inputData.vtu

      - name: ldd
        shell: bash
        run: |
          echo "dll"
          ldd "$TTK_DIR/bin/ttkUserInterfaceBase.dll"

      - name: Test Python example
        continue-on-error: true
        shell: cmd
        run: |
          set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
          cd %GITHUB_WORKSPACE%\examples\python
          dir "%TTK_DIR%\bin\Lib\site-packages"
          set %PYTHONPATH%
          set %PATH%
          python example.py ..\data\inputData.vtu

      - name: Test Python example with call
        continue-on-error: true
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
          cd %GITHUB_WORKSPACE%\examples\python
          python example.py ..\data\inputData.vtu


      - name: Test Python example with pvpython
        continue-on-error: true
        shell: cmd
        run: |
          set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
          cd %GITHUB_WORKSPACE%\examples\python
          pvpython example.py ..\data\inputData.vtu

      - name: Test Python example with bash
        continue-on-error: true
        shell: bash
        run: |
          export PYTHONPATH="$PV_DIR/bin/Lib/site-packages:$TTK_DIR/bin/Lib/site-packages:$CONDA_ROOT/Lib"
          cd $GITHUB_WORKSPACE/examples/python
          python example.py ../data/inputData.vtu

      - name: Test pvpython example
        shell: cmd
        run: |
          set PYTHONPATH=%CONDA_ROOT%\Lib
          set PV_PLUGIN_PATH=%TTK_DIR%\bin\plugins
          cd %GITHUB_WORKSPACE%\examples\pvpython
          pvpython.exe example.py ..\data\inputData.vtu

      - name: Test standalone
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\examples\vtk-c++
          ttkHelloWorldCmd.exe -i %GITHUB_WORKSPACE%\examples\data\inputData.vtu

      - uses: actions/checkout@v3
        with:
          repository: "pierre-guillou/ttk-data"
          ref: "dev"
          path: "ttk-data"
        name: Checkout ttk-data

      - name: Resample large datasets
        shell: pvpython {0}
        working-directory: ./ttk-data
        run: |
          from paraview import simple
          for ds in ["ctBones.vti"]:
              vti = simple.XMLImageDataReader(FileName=ds)
              rsi = simple.ResampleToImage(Input=vti)
              rsi.SamplingDimensions = [128, 128, 128]
              simple.SaveData(ds, rsi)
        env:
          PYTHONPATH: ${{ env.PV_DIR }}\bin\Lib\site-packages;${{ env.CONDA_ROOT }}\Lib

      - name: Run ttk-data Python scripts
        continue-on-error: true
        shell: cmd
        run: |
          set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%TTK_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
          set PV_PLUGIN_PATH=%TTK_DIR%\bin\plugins
          cd ttk-data
          pvpython -u python\run.py

      - name: Test ttk-data Python scripts results [NOT ENFORCED]
        continue-on-error: true
        shell: cmd
        run: |
          cd ttk-data
          type python\res.json
          FC python\hashes\windows.json python\res.json

      - name: Archive cache
        shell: bash
        run: |
          sccache -s
          cd /c/Users/runneradmin/AppData/Local/Mozilla/sccache
          tar czf ttk-sccache.tar.gz cache

      - name: Upload sccache archive
        uses: actions/upload-artifact@v3
        with:
          name: ttk-sccache-windows
          path: C:\Users\runneradmin\AppData\Local\Mozilla\sccache\ttk-sccache.tar.gz
          retention-days: 2
