# This is a basic workflow to help you get started with Actions

name: packaging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branch-ignore:
      - '*'
    tags:
      - 'v*'
      - 'dev*'
      - '*-*-*'
      - '*.*.*'

env:
  pv_v: 5.8.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # TTK dependencies
        sudo apt install -y \
          libboost-system-dev \
          libeigen3-dev \
          libgraphviz-dev \
          libsqlite3-dev \
          graphviz \
          python3-sklearn \
          zlib1g-dev \
          dpkg-dev

    - name: Install Spectra dependency
      run: |
        wget https://github.com/yixuan/spectra/archive/v0.9.0.tar.gz
        tar xvf v0.9.0.tar.gz
        mkdir build_spectra && cd build_spectra
        cmake ../spectra-0.9.0
        sudo make install

    - name: Install ZFP dependency
      run: |
        git clone --depth 1 https://github.com/LLNL/zfp
        mkdir build_zfp && cd build_zfp
        cmake \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          ../zfp
        sudo make -j$(nproc) install

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "pierre-guillou/paraview-ttk"
        version: "tags/${{ env.pv_v }}"
        file: "ttk-paraview-${{ env.pv_v }}-${{ matrix.os }}.deb"

    - name: Install ParaView .deb
      run: |
        sudo apt install ./ttk-paraview-${{ env.pv_v }}-${{ matrix.os }}.deb

    - name: Create & configure TTK build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          -DTTK_ENABLE_DOUBLE_TEMPLATING=TRUE \
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE \
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE \
          $GITHUB_WORKSPACE

    - name: Build TTK
      run: |
        cd build
        make -j$(nproc)

    - name: Package TTK & update package informations
      run: |
        cd build
        cpack -G DEB
        # unpack deb package to access control file
        mkdir tmp
        dpkg-deb --extract ttk.deb tmp
        dpkg-deb --control ttk.deb tmp/DEBIAN
        # modify control file, remove libgcc-s1 dependency
        sed 's/libgcc-s1[^,]*, //g' -i tmp/DEBIAN/control
        # build updated deb package
        dpkg -b tmp ttk-${{ matrix.os }}.deb

    - name: Upload TTK .deb package
      uses: actions/upload-artifact@v2
      with:
        name: ttk-${{ matrix.os }}.deb
        path: build/ttk-${{ matrix.os }}.deb

  test-linux:
    needs: build-linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "pierre-guillou/paraview-ttk"
        version: "tags/${{ env.pv_v }}"
        file: "ttk-paraview-${{ env.pv_v }}-${{ matrix.os }}.deb"

    - name: Fetch TTK .deb artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk-${{ matrix.os }}.deb

    - name: Install generated .deb packages
      run: |
        sudo apt update
        sudo apt install ./ttk-paraview-${{ env.pv_v }}-${{ matrix.os }}.deb
        sudo apt install ./ttk-${{ matrix.os }}.deb

    - name: Test TTK examples
      run: |
        # base layer
        cd $GITHUB_WORKSPACE/examples/c++
        mkdir build && cd build
        cmake ..
        make
        ./ttkExample-c++ -i ../../data/inputData.off
        # VTK layer
        cd $GITHUB_WORKSPACE/examples/vtk-c++
        mkdir build &&  cd build
        cmake ..
        make
        ./ttkExample-vtk-c++ -i ../../data/inputData.vtu
        # pure Python
        cd $GITHUB_WORKSPACE/examples/python
        python3 example.py ../data/inputData.vtu
        # pvpython
        cd $GITHUB_WORKSPACE/examples/pvpython
        pvpython example.py ../data/inputData.vtu
        # standalones
        cd $GITHUB_WORKSPACE
        ttkHelloWorldCmd -i examples/data/inputData.vtu

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install macOS dependencies
      run: |
        # ParaView dependencies
        brew install --cask xquartz
        brew install wget libomp mesa glew qt
        # TTK dependencies
        brew install boost eigen graphviz numpy embree
        python -m pip install scikit-learn

    - name: Install Spectra dependency
      run: |
        wget https://github.com/yixuan/spectra/archive/v0.9.0.tar.gz
        tar xvf v0.9.0.tar.gz
        mkdir build_spectra && cd build_spectra
        cmake ../spectra-0.9.0
        sudo make install

    - name: Install ZFP dependency
      run: |
        git clone --depth 1 https://github.com/LLNL/zfp
        mkdir build_zfp && cd build_zfp
        cmake \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          ../zfp
        sudo make -j$(sysctl -n hw.physicalcpu) install

    - name: Fetch & install ttk-paraview
      run: |
        wget https://github.com/pierre-guillou/paraview-ttk/releases/download/${{ env.pv_v }}/ttk-paraview-${{ env.pv_v }}.pkg
        sudo installer -pkg ttk-paraview-${{ env.pv_v }}.pkg -target /

    - name: Create & configure TTK build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5 \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          -DTTK_ENABLE_DOUBLE_TEMPLATING=TRUE \
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE \
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE \
          $GITHUB_WORKSPACE

    - name: Build TTK
      run: |
        cd build
        make -j$(sysctl -n hw.physicalcpu)

    - name: Package TTK
      run: |
        cd build
        cpack -G productbuild

    - name: Upload .pkg package
      uses: actions/upload-artifact@v2
      with:
        name: ttk.pkg
        path: build/ttk.pkg

  test-macos:
    needs: build-macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install macOS run-time dependencies
      run: |
        # ParaView dependencies
        brew install --cask xquartz
        brew install wget libomp mesa glew qt
        # TTK dependencies
        brew install boost graphviz numpy embree

    - name: Fetch ttk-paraview
      run: |
        wget https://github.com/pierre-guillou/paraview-ttk/releases/download/${{ env.pv_v }}/ttk-paraview-${{ env.pv_v }}.pkg

    - name: Fetch TTK .pkg artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk.pkg

    - name: Install .pkg packages
      run: |
        sudo installer -pkg ttk-paraview-${{ env.pv_v }}.pkg -target /
        sudo installer -pkg ttk.pkg -target /

    - name: Test TTK examples
      run: |
        # base layer
        cd $GITHUB_WORKSPACE/examples/c++
        mkdir build && cd build
        cmake ..
        make
        ./ttkExample-c++ -i ../../data/inputData.off
        # VTK layer
        export CMAKE_PREFIX_PATH=$(brew --prefix qt)/lib/cmake:$CMAKE_PREFIX_PATH
        cd $GITHUB_WORKSPACE/examples/vtk-c++
        mkdir build &&  cd build
        cmake ..
        make
        ./ttkExample-vtk-c++ -i ../../data/inputData.vtu
        # pure Python
        export PYTHONPATH=/Applications/lib/python3.9/site-packages
        export DYLD_LIBRARY_PATH=/Applications/lib:$DYLD_LIBRARY_PATH
        cd $GITHUB_WORKSPACE/examples/python
        python3 example.py ../data/inputData.vtu
        # pvpython
        export PATH=/Applications/bin:$PATH
        cd $GITHUB_WORKSPACE/examples/pvpython
        pvpython example.py ../data/inputData.vtu
        # standalones
        cd $GITHUB_WORKSPACE
        ttkHelloWorldCmd -i examples/data/inputData.vtu

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Install dependencies with conda
      shell: bash
      run: |
        conda install -c conda-forge qt boost eigen spectralib zfp scikit-learn openmp embree3

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - name: Fetch ParaView installer
      run: |
        Invoke-WebRequest `
        -OutFile ttk-paraview.exe `
        -Uri https://github.com/pierre-guillou/paraview-ttk/releases/download/${{ env.pv_v }}/ttk-paraview-${{ env.pv_v }}.exe

    - name: Install ParaView .exe
      shell: cmd
      run: |
        ttk-paraview.exe /S

    - name: Fetch Visual C++ redistribuable run-time
      run: |
        Invoke-WebRequest `
          -OutFile vc_redist.x64.exe `
          -Uri https://aka.ms/vs/16/release/vc_redist.x64.exe

    - name: Configure TTK
      shell: cmd
      run: |
        set CONDA_ROOT="C:\Miniconda"
        set CMAKE_PREFIX_PATH="%CONDA_ROOT%\Library\lib\cmake;%CONDA_ROOT%\Library\share\eigen3\cmake;%CONDA_ROOT%\Library\cmake;%ProgramFiles%\TTK-ParaView\lib\cmake"
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake ^
          -DCMAKE_POLICY_DEFAULT_CMP0092=NEW ^
          -DBUILD_SHARED_LIBS:BOOL=TRUE ^
          -DPython3_ROOT_DIR="%CONDA_ROOT%" ^
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE ^
          -DTTK_BUILD_VTK_WRAPPERS=TRUE ^
          -DTTK_BUILD_STANDALONE_APPS=TRUE ^
          -DTTK_ENABLE_KAMIKAZE=TRUE ^
          -DTTK_ENABLE_DOUBLE_TEMPLATING=TRUE ^
          -DTTK_ENABLE_OPENMP=TRUE ^
          -DTTK_ENABLE_CPU_OPTIMIZATION=FALSE ^
          -DTTK_ENABLE_SHARED_BASE_LIBRARIES=TRUE ^
          -G"Visual Studio 16 2019" ^
          -Tclangcl ^
          ..

    - name: Build TTK
      shell: bash
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Package TTK
      shell: bash
      run: |
        cd build
        cpack -C Release -G NSIS64

    - name: Upload TTK .exe package
      uses: actions/upload-artifact@v2
      with:
        name: ttk.exe
        path: build/ttk.exe

  test-windows:
    needs: build-windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1

    - name: Install run-time dependencies with conda
      shell: bash
      run: |
        conda install -c conda-forge qt boost zfp scikit-learn openmp embree3

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - name: Fetch ParaView installer
      run: |
        Invoke-WebRequest `
        -OutFile ttk-paraview.exe `
        -Uri https://github.com/pierre-guillou/paraview-ttk/releases/download/${{ env.pv_v }}/ttk-paraview-${{ env.pv_v }}.exe

    - name: Fetch TTK .exe artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk.exe

    - name: Install TTK-ParaView and TTK
      shell: cmd
      run: |
        ttk-paraview.exe /S
        ttk.exe /S

    - name: Build & Test native TTK examples
      shell: cmd
      run: |
        :: set environment variables
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PV_DIR=%ProgramFiles%\TTK-ParaView
        set TTK_DIR=%ProgramFiles%\TTK
        set CMAKE_PREFIX_PATH=%TTK_DIR%\lib\cmake;%PV_DIR%\lib\cmake
        set PATH=%PATH%;%PV_DIR%\bin;%TTK_DIR%\bin
        :: base layer
        cd %GITHUB_WORKSPACE%\examples\c++
        mkdir build
        cd build
        cmake -G"Visual Studio 16 2019" -Tclangcl ..
        cmake --build . --config Release --parallel
        Release\ttkExample-c++.exe -i ..\..\data\inputData.off
        :: VTK layer
        cd %GITHUB_WORKSPACE%\examples\vtk-c++
        mkdir build
        cd build
        cmake -G"Visual Studio 16 2019" -Tclangcl ..
        cmake --build . --config Release --parallel
        Release\ttkExample-vtk-c++.exe -i ..\..\data\inputData.vtu
        :: HelloWorld standalone
        ttkHelloWorldCmd.exe -i %GITHUB_WORKSPACE%\examples\data\inputData.vtu

    - name: Test Python examples
      shell: bash
      run: |
        # set environment variables
        export PV_BIN="/c/Program Files/TTK-ParaView/bin"
        export TTK_BIN="/c/Program Files/TTK/bin"
        export CONDA_ROOT="/c/Miniconda"
        export PV_PLUGIN_PATH="$TTK_BIN/plugins"
        export PATH="$PATH:$PV_BIN:$TTK_BIN"
        export PYTHONPATH="$PV_BIN/Lib/site-packages:$TTK_BIN/Lib/site-packages:$CONDA_ROOT/Lib"
        # pure python
        cd $GITHUB_WORKSPACE/examples/python
        python example.py ../data/inputData.vtu
        # pvpython
        cd $GITHUB_WORKSPACE/examples/pvpython
        pvpython.exe example.py ../data/inputData.vtu


  create-release:
    runs-on: ubuntu-latest
    needs: [test-linux, test-macos, test-windows]
    steps:

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Fetch all uploaded artifacts
      uses: actions/download-artifact@v2

    - name: Upload Ubuntu Bionic .deb as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk-ubuntu-18.04.deb/ttk-ubuntu-18.04.deb
        asset_name: ttk-$tag-ubuntu-18.04.deb

    - name: Upload Ubuntu Focal .deb as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk-ubuntu-20.04.deb/ttk-ubuntu-20.04.deb
        asset_name: ttk-$tag-ubuntu-20.04.deb

    - name: Upload macOS .pkg as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk.pkg/ttk.pkg
        asset_name: ttk-$tag.pkg

    - name: Upload Windows .exe as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk.exe/ttk.exe
        asset_name: ttk-$tag.exe
