name: test_build

on:
  push:
    # triggered on pushes on the "dev" branch
    branches:
      - 'dev'
    # triggered on tag pushes with tags beginning with either "v" or "dev"
    tags:
      - 'v*'
      - 'dev*'
      - 'ci*'
      - 'build*'
      - 'test*'
  pull_request:
    # also triggered by pull requests on the "dev" branche
    branches:
      - 'dev'


env:
  PV_TAG: v5.10.1-headless
  PV_REPO: topology-tool-kit/ttk-paraview


jobs:

  # ------------------#
  # Test Ubuntu build #
  # ------------------#
  test-build-ubuntu:
    runs-on: ${{ matrix.os }}
    if: ((github.repository_owner == 'pierre-guillou') == contains(github.ref, 'branch'))
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      CCACHE_DIR: /home/runner/.ccache
      CCACHE_MAXSIZE: 500M
      ASAN_OPTIONS: verify_asan_link_order=0

    steps:
    - name: Test variables
      run: |
        echo event ${{ github.event_name }}
        echo ref ${{ github.ref }}
        echo repository ${{ github.repository }}
        echo owner ${{ github.repository_owner }}
